- when: (ansible_swaptotal_mb | int) + 1 != swap_size | int
  block:
    - name: disable swap
      shell: test -f {{ swap_path }} && swapoff {{ swap_path }} || true
      tags:
        - swap

    - name: create file
      command: 'fallocate -l {{ swap_size }}M {{ swap_path }}'
      tags:
        - swap

    - name: format file
      command: 'mkswap {{ swap_path }}'
      tags:
        - swap

- name: fix permissions
  file:
    path: '{{ swap_path }}'
    owner: root
    group: root
    mode: 0600
  tags:
    - swap

- name: add swapfile to fstab
  mount:
    src: "{{ swap_path }}"
    path: swap
    fstype: swap
    state: present
  tags:
    - swap

- name: enable swap
  command: 'swapon -a'
  changed_when: False
  tags:
    - swap

- name: define swappiness
  sysctl:
    name: vm.swappiness
    value: '{{ swap_swappiness }}'
  tags:
    - swap

- name: vfs pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: '{{ swap_vfs_cache_pressure }}'
  tags:
    - swap
