---
- when: swap_size | int > (ansible_swaptotal_mb | int) + 1
  block:
    - name: Disable active swap
      ansible.builtin.shell: "test -f {{ swap_path }} && swapoff {{ swap_path }} || true"
      tags:
        - swap

    - name: Create swap file
      ansible.builtin.command: "fallocate -l {{ swap_size }}M {{ swap_path }}"
      tags:
        - swap

    - name: Format swap file
      ansible.builtin.command: "mkswap {{ swap_path }}"
      tags:
        - swap

- name: Fix file permissions
  ansible.builtin.file:
    path: "{{ swap_path }}"
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - swap

- name: Mount swap file
  ansible.posix.mount:
    src: "{{ swap_path }}"
    path: swap
    fstype: swap
    state: present
  tags:
    - swap

- name: Enable swap file
  ansible.builtin.command: "swapon -a"
  changed_when: False
  tags:
    - swap

- name: Define swappiness value
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
  tags:
    - swap

- name: Define vfspressure value
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swap_vfs_cache_pressure }}"
  tags:
    - swap

...
